### ISSUE TITLE
calling "manage.py read" results in error

### ISSUE THREAD

**Issue by n8225** [foxmask/th2w#2]
I followed the quickstart to setup th2w.  Additionally I set TIME_ZONE='America/Chicago'. 

When calling "manage.py read" I get the following output:
(this occurs with every RSS feed I have tried so far) Did I skip a step or miss a setting somewhere?

> multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/data/www/th_env/th2w/th2w/read.py", line 38, in reading
    data = ServiceRss.read_data(service.id, **kwargs)
  File "/data/www/th_env/th2w/th2w/service_rss.py", line 65, in read_data
    str(trigger.date_triggered)).to(settings.TIME_ZONE)
  File "/data/www/th_env/lib/python3.5/site-packages/arrow/api.py", line 23, in get
    return _factory.get(*args, **kwargs)
  File "/data/www/th_env/lib/python3.5/site-packages/arrow/factory.py", line 164, in get
    dt = parser.DateTimeParser(locale).parse_iso(arg)
  File "/data/www/th_env/lib/python3.5/site-packages/arrow/parser.py", line 110, in parse_iso
    return self._parse_multiformat(string, formats)
  File "/data/www/th_env/lib/python3.5/site-packages/arrow/parser.py", line 267, in _parse_multiformat
    raise ParserError('Could not match input to any of {0} on \'{1}\''.format(formats, string))
arrow.parser.ParserError: Could not match input to any of ['YYYY-MM-DD', 'YYYY/MM/DD', 'YYYY.MM.DD', 'YYYY-MM', 'YYYY/MM', 'YYYY.MM', 'YYYY', 'YYYY', 'YYYY'] on 'None'
"""

>The above exception was the direct cause of the following exception:

>Traceback (most recent call last):
  File "./manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "/data/www/th_env/lib/python3.5/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/data/www/th_env/lib/python3.5/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/data/www/th_env/lib/python3.5/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/data/www/th_env/lib/python3.5/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/data/www/th_env/th2w/th2w/management/commands/read.py", line 33, in handle
    result.get(timeout=360)
  File "/usr/lib/python3.5/multiprocessing/pool.py", line 608, in get
    raise self._value
arrow.parser.ParserError: Could not match input to any of ['YYYY-MM-DD', 'YYYY/MM/DD', 'YYYY.MM.DD', 'YYYY-MM', 'YYYY/MM', 'YYYY.MM', 'YYYY', 'YYYY', 'YYYY'] on 'None'

**Comment by foxmask** [comment]
Try to :
Disable the triggers that were not yet handle, then enable them back, the redo manage.py read
